config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'posts/top' => 'posts#top'
  get 'posts/food' => 'posts#food'
  get 'posts/look' => 'posts#look'
  get 'posts/enjoy' => 'posts#enjoy'
  get 'posts/miru' => 'posts#miru'


  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  root 'posts#index'

  Rails.application.routes.draw do
    resources :tweets
  end

 
 resources :perfumes



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user


    mount_uploader :image, ImageUploader


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         
         
         has_many :posts, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 }
         

         has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
      like = current_user.likes.create(post_id: params[:post_id]) 
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
      like.destroy
      redirect_back(fallback_location: root_path)
    end
  
  end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end
  
    def new
      @perfume = Perfume.new
    end
  
    def show
      @perfume = Perfume.find_by(id: params[:id])
    end
  
    def create
      @perfume = Perfume.new(perfume_params)
      params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
      if @perfume.save
          flash[:notice] = "診断が完了しました"
          redirect_to perfume_path(@perfume.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def perfume_params
        params.require(:perfume).permit(:id, question: [])
    end
  end
  
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
def top
end

def food
end

def look
end

def enjoy
end

def miru
end








  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)

    post.user_id = current_user.id

    if post.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to :action => "show", :id => post.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to action: :index
  end

  private
  def post_params
    params.require(:post).permit(:place, :address, :image)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id]) 
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagasaki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/dfb1c55515.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="wrapper">
    <header>
      <h1><%= link_to "Find Nagasaki", posts_top_path %></h1>
      <div class="header-list">

      <ul>
      <% if user_signed_in? %>
      <li><%= link_to "マイページ",user_path(current_user.id) %></li>
      <% else %>
      <li><%= link_to "ログイン",new_user_session_path %></li>
<% end %>
        
        <li><%= link_to "食", posts_food_path %></li>
        <li><%= link_to "見る", posts_look_path %></li>
        <li><%= link_to "楽しむ", posts_enjoy_path %></li>
        <li><%= link_to "投稿を見る", posts_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% end %>
        
      </ul>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>

    <div class="push"></div>
    <footer>
     <small>© 2020 ○○○○</small>
  </footer>

  </body>
</html>

app/views/perfumes/index.html.erb
            <h1 class="headline">
            <a>Perfu_me</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", perfumes_path, class: "link" %></li>
            </ul>
        

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_perfume_path, class: "link" %>
        </div>
    

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. どちらかと言うと…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>じっくり考える方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>考えるより行動する方だ</p>
            </div>

            <div class="col-12">
                <p>Question2. 自分の価値観として近い方は…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>周りの人と違う存在でありたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>周りと同じでいたい</p>
            </div>

            <div class="col-12">
                <p>Question3. 人と接するときは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>相手の話をよく聞く方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>自分の話をよくする方だ</p>
            </div>

            <div class="col-12">
                <p>Question4. 大切にしたいのは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>論理性だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>情緒だ</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>

app/views/perfumes/show.html.erb
<div class="intoro">
<h5>診断結果</h5>
<p>あなたにおすすめの香りは…</p>
</div>
<div class="tweet-container">
<div class="tweet">
    <% if @perfume.question == "1111" %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>

    <% elsif @perfume.question == "1112" %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>

    <% elsif @perfume.question == "1121" %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>

    <% elsif @perfume.question == "1122" %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>

    <% elsif @perfume.question == "1211" %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>

    <% elsif @perfume.question == "1212" %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>

    <% elsif @perfume.question == "1221" %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>

    <% elsif @perfume.question == "1222" %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

    <% elsif @perfume.question == "2111" %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>

    <% elsif @perfume.question == "2112" %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>

    <% elsif @perfume.question == "2121" %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>

    <% elsif @perfume.question == "2122" %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>

    <% elsif @perfume.question == "2211" %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>

    <% elsif @perfume.question == "2212" %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>

    <% elsif @perfume.question == "2221" %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>

    <% elsif @perfume.question == "2222" %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>

    <% end %>

</div>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :place %>
    <%= f.text_field :place, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/posts/enjoy.html.erb
<div class="huis">
<h3>1.ハウステンボス</h3><br>
<%= image_tag 'huis.jpeg', :size => '500x330' %>
<br>
佐世保市にある長崎県を代表するテーマパーク！
オランダの街並みが再現されていて、ゴンドラに乗れたり、テーマパークならではのアトラクションを楽しめます。<br>
夜になると日本最大級ともいわれるイルミネーションで辺りが包まれます。>>>>>
<a href="https://www.huistenbosch.co.jp/" target="_blank">HP</a>
</div>


<div class="enjoy">
ハウステンボス
ビードロ作り
</div>

app/views/posts/food.html.erb
<div class="burger">

<h3>1.佐世保バーガー BigMan下京町本店</h3><br>
<%= image_tag 'BigMan', :size => '500x330' %><br>
「バナナマンのせっかくグルメ」でも紹介された老舗の佐世保バーガーのお店！
実は佐世保バーガーは決まったスタイルはないので、お店によって味が違うのも楽しめるポイント。<br>
BigManの一番の人気メニューは、「元祖ベーコンエッグバーガー(825円)!! >>>>>
<a href="http://www.sasebo-bigman.jp/" target="_blank">お店HP</a>
</div>

<br>
<hr class="hr1">

<div class="china">
<h3>2.長崎新地中華街</h3><br>
<%= image_tag 'chinatown.jpeg', :size => '500x330' %><br>
横浜・神戸と並ぶ日本三大中華街のひとつ、長崎新地中華街。
東西、南北あわせて約250mの十字路に中華料理店をはじめ、中国菓子や中国雑貨など約40店舗が軒を連ねています。<br>

異国情緒漂う街並みを楽しみながら食べ歩きするのもおすすめ。
長崎名物「ちゃんぽん」や「皿うどん」も美味しい！ >>>>>
<a href="http://www.nagasaki-chinatown.com/" target="_blank">HP</a>
</div>

<br>
<hr class="hr1">

<div class="hirado">
<h3>3.平戸瀬戸市場 シーサイドカフェ</h3><br>
<%= image_tag 'ichiba.png', :size => '500x330' %><br>
新鮮な魚や特産品が集まる集まる市場の中にあるレストラン。平戸で獲れた地物の食材を使った美味しい海鮮丼が人気！
１階には市場があり、ショッピングも楽しめます。<br>
海沿いに位置しているのでロケーションも絶好です！！>>>>>
<a href="https://setoichiba.com/restaurant/" target="_blank">HP</a>
</div>

app/views/posts/index.html.erb
<div class=toukou>
<h1>投稿一覧</h1>
</div>



<%= link_to "新規投稿へ", new_post_path %>
<div class="posts-container">
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %><br>
<% end %>

<div class="post1">
  <% @posts.each do |t| %>
    <div class="usagi">
    <%= image_tag t.image_url, size: "250x200" if t.image? %><br>

    <img src=<%= t.user.image %> class = "img", width: '50%', height: '50%' >

    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.user.email %>

    <div class="post">
      <%= t.place %><br>
      <%= t.address %>
      

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
            <i class="fas fa-heart fa-2x" style="color:#db7093"></i><%= t.likes.count %><br>
          <% end %>
      <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart fa-2x" style="color:#db7093"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart fa-2x" style="color:#db7093"></i><%= t.likes.count %>
  <% end %>


      <%= link_to "詳細へ", post_path(t.id) %>
      
    </div>

    <%= link_to "編集する", edit_post_path(t.id) %>
    <%= button_to "削除する", post_path(t.id), method: :delete %>
    </div>
    <% end %>
  </div>


  <%= link_to "ログイン", posts_path %>
<%= link_to "新規登録", new_user_registration_path %>
</div>

app/views/posts/look.html.erb
<div class="guraba">
<h3>1.グラバー園</h3><br>
<%= image_tag 'guraba.jpeg', :size => '500x330' %><br>

長崎港を見下ろすことができる丘に位置し、異国情緒あふれる長崎屈指の人気観光スポット。<br>
国指定重要文化財の旧グラバー住宅・旧リンガー住宅・旧オルト住宅をメインに、市内に点在していた6つの明治期の洋館を移築し復元しています。<br>
園内各所が花々で彩られていて写真映えするスポットばかり！>>>>>
<a href="https://glover-garden.jp/" target="_blank">HP</a>
</div>

<br>
<hr class="hr1">

<div class="unzen">
<h3>2.雲仙地獄</h3><br>
<%= image_tag 'unzen.jpeg', :size => '500x330' %><br>
全国でも有数な温泉地のひとつでもある雲仙市。定番観光スポットといったら雲仙地獄！<br>
雲仙地獄は硫黄の香りに包まれており、蒸気がたくさん上がっているので白い煙に包まれた景色を楽しむことができます。<br>
温泉卵やレモネードも買うことができるので一緒に食べるのもおすすめ。>>>>>
<a href="https://www.unzen.org/" target="_blank">HP</a>
</div>

<br>
<hr class="hr1">

<div class="dejima">
<h3>3.出島</h3><br>
<%= image_tag 'dejima.jpeg', :size => '500x330' %><br>
日本が江戸時代の約200年間、鎖国政策をとり西洋との外交を絶っていた時代に唯一開かれていた貿易の窓口である出島。<br>
現在は、19世紀初めの江戸から明治にかけての建物が再現されていて、様々な時代の街並みを楽しむことができるようになっています。<br>
出島ワーフと呼ばれるベイサイドエリアは、夜になると夜景が綺麗！>>>>>
<a href="https://nagasakidejima.jp/" target="_blank">HP</a>
</div>

app/views/posts/miru.html.erb
投稿一覧ページ見せたい

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <div class="top">
  <h3>新規投稿ページ</h3>
  </div>


  <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :place, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :住所 %>
    <%= f.text_field :address, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

<div class="m">
  <%= f.submit "投稿する" %>
  </div>
  <% end %>
  
  <%= link_to "一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<div class="detail">
<h3>投稿詳細</h3>
</div>


<div class="post">
  <p><%= @post.place %></p>
  <p><%= @post.created_at %></p>
  <% if user_signed_in? %>
  <% if current_user.already_liked?(@post) %>
    <%= link_to tweet_path(@post), method: :delete do %>
      <i class="fas fa-heart fa-2x" style="color:#db7093"></i><%= @post.likes.count %>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(@post), method: :post do %>
      <i class="far fa-heart fa-2x" style="color:#db7093"></i><%= @post.likes.count %>
    <% end %>
  <% end %>
<% else %>
<i class="far fa-heart fa-2x" style="color:#db7093"></i><%= @post.likes.count %>
<% end %>
<%= link_to "編集する", edit_post_path(@post.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<%= link_to "Post一覧に戻る", posts_path %>

app/views/posts/top.html.erb
<div class="slide">
     <div class="slide-image"></div>
     <div class="slide-image"></div>
     <div class="slide-image"></div>
</div>

<div class="setsumei">
海に山、美しい自然と観光資源に囲まれた”長崎県”。
長崎についてもっと知ってみませんか?
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="mypage">
<h1>MY PAGE</h1>

<img src=<%= @user.image %> class = "img", width: '50%', height: '50%' >
<p>name : <%= @user.name %></p>

<p>profile : <%= @user.profile %></p>


<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>
</div>


<h2>投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.place %>
  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
<% end %>

<h2>いいねした投稿</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.place %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
<% end %>


<%= link_to "投稿一覧に戻る", posts_path %>